version: '2'

services:
  bot:
    build: .
    ports:
      - "2967:2967"
    volumes:
      - ./db/:/bot/db/
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/bot/db/
